<?php
    include("cv_sprogs.php");
        debutPage("CV - Andy LECOQ", "std", "css/bootstrap.min.css css/app.css", "", "img/favicon.ico");
        div("container");
            div("header");
                div("row");
                    div("col-xs-3");
                        echo img("img/moi.jpeg" , "Andy LECOQ", "146", "", "picture");
                    findiv();
                    div("col-xs-9");
                        h1("Andy ". s_span("LECOQ", "name"), "name");
                        h3("&Eacute;tudiant en recherche de stage", "caption pull-right");
                    findiv();
                findiv();
            findiv();
            div("content");
                div("row");
                    div("col-xs-3 side");
                        div("address");
                            echo "1 rue Michel Fourr&eacute; \n";br();
                            echo "Cormeray \n";br();
                            echo "49100 Angers";br();
                        findiv();
                        div("spacer");findiv();
                        ul("class='infos'");
                            li("Tel");
                            debutli("06.27.18.84.33", "class='divider'");finli();
                            li("Email");
                            debutli("lecoqandy@gmail.com", "class='divider'");finli();
                            li("N&eacute; le 07/12/1994");
                            li("20 ans");
                            debutli("&nbsp;", "class='spacer'"); finli();
                            li("C&eacute;libataire");
                            li("Permis avec v&eacute;hicule personnel");
                        finul();
                    findiv();
                    div("col-xs-9 main");
                        div("page-header"); 
                            h2("D&eacute;veloppeur informatique");
                        findiv();
                        div("", "pro");
                            div("label dark");
                                echo "Exp&eacute;rience professionnelle <i class='fa fa-suitcase'>&nbsp;</i>";
                            findiv();
                            div("row");
                                div("col-xs-12");
                                    ul();
                                        
                                        debutli("Janvier 2014 - Juin 2014 &bull; Lyc&eacute;e de l'Hyr&ocirc;me &bull; Projet &eacute;tudiant", "class='label dark'"); finli();
                                        li("&bull; D&eacute;veloppement d'une application Android dans le but de g&eacute;rer des &eacute;levages de volailles.");
                                        li("&bull; Etude d'un cahier des charges et mod&eacute;lisation d'une solution");
                                        li("&bull; Projet comptabilis&eacute; dans la validation du BTS");
                                        li("&bull; Langage utilis&eacute; : JAVA - Android");
                                        debutli("&nbsp;", "class='spacer'"); finli();
                                        debutli("Juin 2013 - Juillet2013 &bull; LOGOSAPIENCE &bull; Stage d&eacute;veloppement", "class='label dark'"); finli();
                                        li("&bull; D&eacute;veloppement d'un programme de traitement audio.");
                                        li("&bull; Recherche de librairies cross-plateforme li&eacute;es à la gestion multim&eacute;dia");
                                        li("&bull; Langage utilis&eacute; : C++");
                                    finul();
                                findiv();
                            findiv();
                        findiv();
                        div("", "studies");
                            div("label");
                                echo "Formation <i class='fa fa-graduation-cap'>&nbsp;</i>";
                            findiv();
                            div("row");
                                div("col-xs-12");
                                    ul();
                                        li("2014 - 2015 &bull; ".b("Licence Professionnelle &laquo; Logiciels libres &raquo;")." &bull; Facult&eacute; des sciences - Angers (49)");
                                        li(em("&bull; Formation en cours"));
                                        debutli("&nbsp;", "class='spacer'"); finli();
                                        li("2012 - 2014 &bull; ".b("BTS Informatique (IRIS)")." &bull; Lyc&eacute;e de l'Hyr&ocirc;me - Chemill&eacute; (49)");
                                        li(em("&bull; Informatique et R&eacute;seaux pour l'Industrie et les Services techniques"));
                                        debutli("&nbsp;", "class='spacer'"); finli();
                                        li("2011 - 2012 &bull; ".b("Baccalaur&eacute;at Scientifique")." &bull; Lyc&eacute;e Sainte Agn&egrave;s - Angers (49)");
                                        li(em("&bull; Option : Sciences et Vie de la Terre"));
                                    finul();
                                findiv();
                            findiv();
                        findiv();
                        div("", "skill");
                            div("label light");
                                echo "Comp&eacute;tences <i class='fa fa-trophy'>&nbsp;</i>";
                            findiv();
                            div("row");
                                div("col-xs-6");
                                    ul();
                                        debutli("Langues", "class='label light'");finli();
                                        li("Anglais - Technique");
                                        li("Espagnol - Scolaire");
                                        debutli("R&eacute;seau", "class='label light'");finli();
                                        li(em("Mise en place d'un serveur web, DNS, DHCP..."));
                                        debutli("Logiciel", "class='label light'");finli();
                                        li("Eclipse -".b("Netbeans")." - Android Studio - QtCreator - Sublime Text - Suites bureautiques");
                                    finul();
                                findiv();
                                div("col-xs-6");
                                    ul();
                                        debutli("D&eacute;veloppement logiciel", "class='label light'");finli();
                                        li("Objet : C++, ".b("JAVA")." (+ Android), PHP");
                                        li("WEB : CSS, HTML, PHP, js");
                                        li("Requ&ecirc;tes structur&eacute;es : SQL");
                                        li("Autres : C, sh");
                                        li("Framework : CakePHP, Foundation, Bootstrap");
                                        debutli("Syst&egrave;me d'exploitation", "class='label light'");finli();
                                        li(b("Windows, Linux")." (Ubuntu, Debian, CentOS), Andoid");
                                    finul();
                                findiv();
                            findiv();
                        findiv();
                        div("", "interests");
                            div("label gray");
                                echo "Centres d'int&eacute;r&ecirc;t <i class='fa fa-rocket'>&nbsp;</i>";
                            findiv();
                            div("row");
                                div("col-xs-6");
                                    ul();
                                        debutli("Nouvelles technologies", "class='label'");finli();
                                        li("Veille technologique permanente");
                                        li("Passionn&eacute; de Linux et Android");
                                    finul();
                                findiv();
                                div("col-xs-6");
                                    ul();
                                        debutli("Sport", "class='label'");finli();
                                        li("Arbitrage officiel de basket-ball, niveau d&eacute;partemental");
                                    finul();
                                findiv();
                            findiv();
                        findiv();
                    findiv();
                findiv();
            findiv();
            div("validator");
                valid();
                br();
                pdf();
                br();
                afficherDate();
            findiv();
        findiv();
        script("script.js");
    finPage();
?>
